### ISSUE TITLE
Examples and paper trail for the escalation process

### ISSUE THREAD

**Issue by EvansJonathan** [CVEProject/cveproject.github.io#15]
GOAL: Clarify existing language.
CHANGE: Page 5 (Section 1.2) of the current CNA rules states:
"In cases where requests or issues cannot be resolved by a given CNA, the issues are escalated to the next higher level CNA."
Provide examples of the kinds of issues that might cause escalations. Also, create rule that requires some kind of paper trail for attempts to work with the CNA.
OUTCOME: Less vague or confusing language.

**Comment by kurtseifried** [comment]
I would say 2 main situations:

1) CNA is really non responsive within a given time frame (weeks/months) - tough with small projects/etc.
2) CNA doesn't think it is a vuln - parent(s) act as arbitrator? 

this goes back to the CNA federation definition, just walk the chain up the parents, once you hit MITRE and they say no (aka the supreme court of CVE) yer done.

**Comment by dadinolfi** [comment]
Suggestion: change 2.2.4 to read 

4.	Be responsive to inquiries from all CNAs and document those interactions in some way (archiving email correspondence or tracking via a trouble ticket would be sufficient, for example).

**Comment by dadinolfi** [comment]
Suggestion: change the third paragraph of section 1.2 to read

In cases where requests or issues cannot be resolved by a given CNA, the issues are escalated to the next higher-level CNA. (Examples of such issues would be a CNA being unresponsive beyond expected timeframes or a disagreement with a CNA over whether or not an issue is a vulnerability.) Requests and issues at the Sub-CNA level can be elevated to Root CNAs, and requests and issues at the Root CNAs can be elevated to the Primary CNA. The same flow, from Sub-CNAs to Root CNAs to the Primary CNA, is followed to alert the next higher CNA when CVEs are assigned, or when reporting other programmatic data. The Primary CNA provides blocks of IDs to Root CNAs, and Root CNAs provide blocks of IDs to Sub-CNAs.
