### ISSUE TITLE
Tie JSON updates schedule to CNA Rules update schedule.

### ISSUE THREAD

**Issue by EvansJonathan** [CVEProject/cveproject.github.io#22]
GOAL: Predictable change schedule
CHANGE: Tie JSON updates schedule to CNA Rules update schedule.
OUTCOME:  CNAs will know how to allocate their resources;  the schema will be updated based on the new requirements defined by the rules update.

**Comment by kurtseifried** [comment]
agreed. I'd suggest we do like the Linux Kernel, have a stable train (even major numbers) and a dev train (odd major numbers) e.g. 4.x is stable, 5.x is devel. We could then go nuts with the devel train, but keep the stable train, well, stable, e.g. updates very 6 or 12 months, announced well in advance (90 day warning?) etc. People who support dev get the better data, so the incentive is there.

**Comment by dadinolfi** [comment]
Suggestion: adding to Appendix B
The JSON schema will be reviewed periodically. The review cycle will follow a schedule similar to this example:
First 30 days (September)
•	Open comment period including Board and CNAs.
•	One or two Automation WG calls specifically set aside for discussion of proposed changes.
•	At the end of this period, no additional suggestions will be included in the revision cycle.

Next 30 days (October)
•	The community will work in one-week sprints (WG meetings and mailing list discussions) with a subset of the proposed revisions discussed during each sprint. Each subset is only to be discussed during that sprint.
•	There will be four total sprints (making this part a four-week process).
•	At the end of a sprint, if something was not resolved or discussed, it will not be included in the revision.
•	When something is resolved, any changes based on it are included within the development branch at that time.
At the end of all sprints, the JSON format will be finalized and sent to the Board for approval.
 
Next 60 days (November and December)
•	CNAs can use the development branch for testing new features and changes

The new JSON format would take effect on January 1 of the next year. This will give CNAs two months to implement any changes to their processes that become needed after the JSON format revised.
