### ISSUE TITLE
Fix typo in 2.2.9

### ISSUE THREAD

**Issue by EvansJonathan** [CVEProject/cveproject.github.io#35]
GOAL: Fix typos.
CHANGE:
	- 2.2.9 has a typo at the end.
OUTCOME: Correct grammar and spelling.

**Comment by dadinolfi** [comment]
Current: Publish required CVE information in a standard format and presentation, to be determined and managed by the CVE Project (CNAs, board?)

New: Publish required CVE information in a standard format and presentation style. This format and style will be determined and managed by the CVE Board.

**Comment by dadinolfi** [comment]
Updated CNA Rules draft.
