### ISSUE TITLE
Notify requester when a CVE ID has been assigned.

### ISSUE THREAD

**Issue by EvansJonathan** [CVEProject/cveproject.github.io#36]
GOAL: Notify requester when a CVE ID has been assigned.
CHANGE: Create a requirement that the original requester of a CVE ID will be notified when the CVE ID has been assigned.
OUTCOME: Improved communication between CNAs and CVE requesters.

**Comment by EvansJonathan** [comment]
I believe this is covered by 2.2.5:

> When a vulnerability is reported to the CNA and a CVE ID is assigned to that vulnerability, provide the CVE ID to the reporter. This rule does not override any embargo rules established by the CNA.

**Comment by kurtseifried** [comment]
can we close this?

**Comment by dadinolfi** [comment]
Unless there is another aspect to this suggestion not covered by the existing rules, this will be closed without any additions to the document.

**Comment by david-waltermire** [comment]
This relates to issue #40 and should be handled based on the workflow there.
