### ISSUE TITLE
Define how quickly CNAs are expected to submit entries after publishing an advisory

### ISSUE THREAD

**Issue by EvansJonathan** [CVEProject/cveproject.github.io#38]
GOAL: Make CVE information available in a timely manner
CHANGE: Require submission of entry within 24 hours of the vulnerability being made public.
OUTCOME:  The entry information will be available when it is needed.

**Comment by kurtseifried** [comment]
I assume submission of entry means submission to the parent CNA? MITRE? MITRE doesn't want to directly talk to 100,000 sub CNAs... Can you please clarify this

**Comment by EvansJonathan** [comment]
From the Meeting Minutes:

> The current CNA rules do not stipulate a specific time by which a CNA should update their upstream CNA after a CVE ID has been made public. MITRE asked the Board for guidance on the most time a CNA can wait. The Board suggested that CNAs should update their upstream CNAs within 24 hours of the publication of a CVE ID. This recommendation will be added to the list of updates to be considered for the next CNA Rules update.

http://cve.mitre.org/data/board/archives/2017-04/msg00003.html

**Comment by dadinolfi** [comment]
Suggestion: add section 2.1.4

4.	CNAs should update their upstream CNAs within 24 hours of the publication of a CVE ID. (The meaning of “publication” is discussed in Appendix A.)

___

The meaning of publication in Appendix A is given as:
A CVE ID is published when the CVE ID itself is used in a public forum outside of CVE. A CVE ID entry may not be populated when someone publishes the CVE ID. The CVE ID entry will not be populated until the minimal required information for CVE assignment has been communicated to the Primary CNA. Note: if the CVE ID is used publicly before anyone has updated the Primary CNA with the CVE ID information, the CVE ID entry may show as "reserved" or nonexistent in the CVE List until the Primary CNA has been updated.
