### ISSUE TITLE
Make JSON the preferred format

### ISSUE THREAD

**Issue by EvansJonathan** [CVEProject/cveproject.github.io#39]
GOAL:  
CHANGE Make the JSON format the preferred format.  Should JSON be the only supported format?  If so, how long should the phase out process be?
OUTCOME:  Reduced overhead of supporting and maintaining multiple format.

**Comment by kurtseifried** [comment]
I think JSON should be the first class format, but people are welcome to mangle it and publish it in ways they see fit (e.g. the existing cve.mitre.org publication via CSV/xml/etc.).

**Comment by dadinolfi** [comment]
Suggestion: add to Appendix B the following:

The preferred format for submitting CVE assignment information is using the JSON schema described here: https://github.com/CVEProject/automation-working-group/blob/master/cve_json_schema/DRAFT-JSON-file-format-v4.md
