### ISSUE TITLE
Re section 4.1(4)

### ISSUE THREAD

**Issue by kurtseifried** [CVEProject/cveproject.github.io#4]
To quote:

The CNA must follow coordinated disclosure practices as determined by the community which they serve. Coordinated disclosure practices reduce the likelihood that duplicate or inaccurate information will be introduced into CVE. 

We should probably change "must" to "may" or redefine this a bit (e.g. a CNA with a 90 day disclosure rule meets a vendors that needs more time to fix things, what happens then?).

**Comment by dadinolfi** [comment]
Per Issue #23, changing "must" to "should".
