### ISSUE TITLE
Add explicit how-to steps for submitting CVE entries to the Primary CNA

### ISSUE THREAD

**Issue by EvansJonathan** [CVEProject/cveproject.github.io#40]
GOAL: Improve process descriptions.
CHANGE: Add explicit how-to steps for submitting CVE entries to the Primary CNA.
OUTCOME: CNAs will have clear processes to follow.

**Comment by kurtseifried** [comment]
to be clear the primary CNA is MITRE? I would suggest that the GIT process will come to the front for scalability and ease of use.

**Comment by dadinolfi** [comment]
Suggestion: Add to Appendix B

Sending CVE Assignment Information to MITRE
MITRE is the Primary CNA as of this writing. The following describes the methods for submitting CVE assignment information to MITRE.
Using the CVE Request Web Form
The CVE Request web form is the preferred method for submitting CVE assignment information as of this writing.
This method supports all three file types (flat file, CSV file, and JSON).
This method is suited to both new and updated submissions.
The form has limits on form field sizes, which may cause problems when submitting multiple CVE ID requests at one time.
Using the cve@mitre.org email address.
This method supports all three file types.
This method is suited to new submissions only.
Using Git (Experimental)
This method supports CVE JSON only.
Note, one should avoid files with MS-DOS style line endings (CR/LF).
This method is suited to both new and updated submissions.

Submitting through the CVE Request web form
Visit https://cveform.mitre.org/
Select “Notify CVE about a publication” and enter your e-mail address.
Fill in the form.
“Link to the advisory” and “CVE IDs of vulnerabilities to be published “ fields are required.
The assignment information (in Flat File, CSV, or JSON format) goes in the “Additional information and CVE ID description updates” field. [Alternatively, you can send the assignment information as a file attachment in a reply to an e-mail message generated by MITRE’s ticketing system when the submission has been received.]
Enter the security code.
Press “Submit Request”.

**Comment by EvansJonathan** [comment]
Instead of including the individual steps, I suggest we make a requirement that the Root and Primary CNAs publish a document containing the steps to submit an entry to them.  This way, if the steps change, we won't have to change the Rules document.

**Comment by david-waltermire** [comment]
We may want to support a shared service approach for the Primary and Roots, providing a single path for submitting a CVE that would lead to the appropriate CNA handling the request. This would keep it simple for the user. This is something we can pilot in the Git pilot, trying out various approaches.

**Comment by dadinolfi** [comment]
Added Section 3.1.1.5:

5.	Provide public documentation describing the specific process for submitting CVE assignments and other CVE requests.

The suggestion made above will be moved to a document posted on the MITRE CVE website. This will allow the process to change as needed, but it will be clear that the process to submit CVE requests should be transparent.

**Comment by david-waltermire** [comment]
Shouldn't this be kept open until the actual solution is completed? If we want to post a document to the website, then close this when that occurs.

-------- Original Message --------
