### ISSUE TITLE
Define hardware

### ISSUE THREAD

**Issue by EvansJonathan** [CVEProject/cveproject.github.io#43]
GOAL: Better define terms.
CHANGE: Better define "hardware" with regard to CVE.
OUTCOME: Regularized terminology.

**Comment by dadinolfi** [comment]
In CNA Rules 1.1, there is no explicit definition of "hardware". The only reference to hardware is in the definition of "vulnerability" in Appendix A, and that entry offers no clarity on what we mean by hardware.

In the CVE FAQ <http://cve.mitre.org/about/faqs.html>, there is also only one reference to "hardware", but it is slightly clarified with "(e.g., firmware)". 

Wikipedia <https://en.wikipedia.org/wiki/Electronic_hardware> has a description of "electronic hardware" as follows:
Electronic hardware consists of interconnected electronic components which perform analog or logic operations on received and locally stored information to produce as output or store resulting new information or to provide control for output actuator mechanisms.
Electronic hardware can range from individual chips/circuits to distributed information processing systems. Well designed electronic hardware is composed of hierarchies of functional modules which inter-communicate via precisely defined interfaces.

This description is closest to the intent of CVE scope. CVE IDs would be assigned to vulnerabilities in electronic hardware that affect the function of those components, just as for pure software. Perhaps we should use this definition/description in the rules?

**Comment by dadinolfi** [comment]
Updated CNA Rules draft.
