### ISSUE TITLE
Remove CVE ID assignment requirements for Root CNAs

### ISSUE THREAD

**Issue by EvansJonathan** [CVEProject/cveproject.github.io#44]
GOAL: Increase adoption of CVE
CHANGE: Remove CVE ID assignment requirements for Root CNAs
OUTCOME: Organizations willing to be a Root CNA but without the resources to handle CVE ID assignment will become join.

**Comment by dadinolfi** [comment]
Suggestion: 
Add to 3.1.1(3):
Alternately, if a Root CNA does not themselves assign CVE IDs, they MUST escalate CVE ID requests up to the Primary CNA (or direct those requests accordingly).
