### ISSUE TITLE
Define what metrics CNAs need to report

### ISSUE THREAD

**Issue by EvansJonathan** [CVEProject/cveproject.github.io#46]
GOAL:  Inform CNAs of what is expected of them
CHANGE:  More specific guidance on what information needs to be reported back to the Primary and what formats.  Templates need justification and explanation of what we are using those data for. Data needs meaning and results should be actionable.
OUTCOME:  Improved ability to assess the health of the CNA initiative.

**Comment by dadinolfi** [comment]
First, we need to decide what data we want to collect from CNAs. Here are some initial suggestions and rationale.

For All CNAs
- Number of unique vulnerability reports received from external parties (assigned and not assigned CVE IDs)
This gives us an idea of how much vulnerability disclosure activity there is in each CNA which we can then extrapolate to sector or some other category of CNA.
- Average time between assignment of CVE ID and publication of CVE ID entry
Again, taken in aggregate, we get an idea for what the common time frames are, which can inform discussions of best practice.

For Root CNAs
- Number of times an issue was escalated to the Root CNA
How much of a Root CNA's time is spent dealing with escalations? Does it scale with the number of Sub-CNAs they have? Does it vary between sectors?
- Categories of escalated issues and percentage of total: Dispute, Responsiveness, Misuse of CVE
What is the nature of the issues that Root CNAs are addressing, which can inform training, documentation, and process improvement.
- List of Sub-CNAs and New Sub-CNAs this quarter
Good housekeeping, this forces the periodic update of the full CNA directory.
