### ISSUE TITLE
Re section 4.1(3)

### ISSUE THREAD

**Issue by kurtseifried** [CVEProject/cveproject.github.io#5]
The CNA must be an established distribution point or source for first-time product
vulnerability announcements (which may concern their own products). In keeping with
the CVE requirement to identify public issues, the CNA must only assign CVEs to
security issues that will be made public. (Refer to the definition of “vulnerability” in
Appendix A for clarification on what products should and should not be considered when
assigning a CVE ID.) 

We already have CNA's that are individuals and/or security research firms (Larry Cashdollar/BlackDuck/HackerOne) so we should revamp and expand this definition.

**Comment by kurtseifried** [comment]
Also section 4.1(2) needs to be modified with respect to this

**Comment by dadinolfi** [comment]
Added to 4.1(2):
c.	an established bug bounty service provider or
d.	an established vulnerability research team or
e.	an independent vulnerability researcher.

**Comment by dadinolfi** [comment]
For 4.1(3), the definition covers researchers and other security firms in that, if they are assigning CVE IDs, they should be publishing public references to the issues they are discovering.

Just to be sure, adding the following to 4.1(3):
If the CNA is disclosing vulnerabilities for products or projects not their own (and not covered by another CNA), they must consistently publish a public vulnerability announcement for each assignment.
