### ISSUE TITLE
Add language setting expectations on when downstream developers should coordinate with upstream developers.

### ISSUE THREAD

**Issue by dadinolfi** [CVEProject/cveproject.github.io#51]
GOAL: Clarify the preference for CNAs to coordinate their disclosures of vulnerabilities in third-party code with those third-parties.
CHANGE: Add language setting expectations on when downstream developers should coordinate with upstream developers. If a downstream vendor lets us know that the issue affects a shared piece of code and the CVE is written to the shared code, the upstream developer should also use that same CVE ID, not create another which it seems is sometimes the case (which is already a counting rule).
OUTCOME: Fewer duplicate CVE IDs when code is shared between projects/products.

**Comment by dadinolfi** [comment]
Comment from Kurt Seifried:

So in the software world (both open and closed) there's a lot of dead/uncommunicative vendors/projects, so I wouldn't make it hard requirement to have communications, but I would maybe say something like "CNAs MUST make a reasonable effort to communicate the flaw to upstream". If projects don't make it easy, or are not communicative for security flaws then that's on them, we can't make CNAs backstop all of them.

**Comment by kurtseifried** [comment]
Also for downstream there's literally a million people downstream in some cases, some make things that matter, some don't (e.g. some random app that embedded a copy of libxml so it compiles cleanly on windows and has 4 users). I would suggest adding some guidance/advice but not making it an actual requirement at this time.

**Comment by dadinolfi** [comment]
Suggestion: Create section 2.2.10 in Communication Rules for CNAs

10.	If a CVE ID is being assigned to a vulnerability in shared code, the CNA MUST make a reasonable effort to notify the upstream maintainer of that shared code. (For example, if an operating system vendor discovers a vulnerability in a printing library they distribute, in addition to assigning the CVE ID to the vulnerability, they should attempt to contact the upstream developer. This will help avoid duplicate CVE ID assignments as well as ensure others that are affected by the vulnerability will be made aware of it.)

**Comment by EvansJonathan** [comment]
> If a CVE ID is being assigned to a vulnerability in shared code, the CNA MUST make a reasonable effort to notify the upstream maintainer of that shared code. (For example, if an operating system vendor discovers a vulnerability in a printing library they distribute, in addition to assigning the CVE ID to the vulnerability, they should attempt to contact the upstream developer. This will help avoid duplicate CVE ID assignments as well as ensure others that are affected by the vulnerability will be made aware of it.)

Is this meant to only apply to vendor CNAs?  If not, what does "shared code" mean in the context of non-vendor CNAs?

**Comment by dadinolfi** [comment]
Updated Suggestion: Create section 2.2.10 in Communication Rules for CNAs

If a CVE ID is being assigned to a vulnerability, the CNA MUST make a reasonable effort to notify the maintainer of the code in which that vulnerability exists. (If the CNA is assigning for a vulnerability in their own product or codebase, this is inherently done.) For example, if an operating system vendor discovers a vulnerability in a printing library they distribute, in addition to assigning the CVE ID to the vulnerability, they should attempt to contact the upstream developer. This will help avoid duplicate CVE ID assignments as well as ensure others that are affected by the vulnerability will be made aware of it.
